apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: agentic-ai
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  title: Agentic AI
